spring:
  application:
    name: shopping-cart
  config:
    import: 
      - optional:file:.env[.properties]
      - "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}/eureka/
