spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: shopping-cart
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/shopping_cart
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/microservicios-ecommerce
client:
  product-service:
    url: ${PRODUCT_HOST}/api/v1
server:
  port: 8003
