spring:
  config:
    import: classpath:.env.test[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL} 
    username: ${SPRING_DATASOURCE_USERNAME} 
    password: ${SPRING_DATASOURCE_PASSWORD} 
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_HOST}/realms/${KEYCLOAK_REALM}
client: 
  product-service:
    url: ${PRODUCT_HOST}/api/v1
KEYCLOAK:
  HOST: ${KEYCLOAK_HOST} 
  REALM: ${KEYCLOAK_REALM} 
  CLIENT_ID: backend-admin
  CLIENT_SECRET: X1in1OkB5BfBmvcdPcCo4wNmGZgHKqvf


